### ISSUE TITLE
Infinite loop in frontend

### ISSUE THREAD

**Issue by elazarg** [pepper-project/pepper#1]
A trace loop:

```
at ccomp.parser_hw.CCompiler.genericFunctionCall(CCompiler.java:1039)
at ccomp.parser_hw.CCompiler.getExpr(CCompiler.java:947)
at ccomp.parser_hw.CCompiler.getExpr(CCompiler.java:961)
at ccomp.parser_hw.CCompiler.getExpr(CCompiler.java:782)
at ccomp.parser_hw.CCompiler.expandStatement(CCompiler.java:649)
at ccomp.parser_hw.CCompiler.expandStatement(CCompiler.java:624)
at ccomp.parser_hw.CCompiler.getExpr(CCompiler.java:840)
at ccomp.parser_hw.CCompiler.expandStatement(CCompiler.java:649)
at ccomp.parser_hw.CCompiler.getExpr(CCompiler.java:862)
at ccomp.parser_hw.CCompiler.expandStatement(CCompiler.java:649)
at ccomp.parser_hw.CCompiler.expandStatement(CCompiler.java:624)
at ccomp.parser_hw.CCompiler.genericFunctionCall(CCompiler.java:1039)
```

**Comment by kwantam** [comment]
Thanks for reporting this :+1:

Do you have a test case you could share that triggers this issue?

**Comment by elazarg** [comment]
It is a recursive program, so I assume that's an unbounded number of inlining. It's just that there is a clear warning for unbounded loops, and there isn't one for unbounded recursion.

**Comment by elazarg** [comment]
```
// adapted from code by Rob Pike
// www.cs.princeton.edu/courses/archive/spr09/cos333/beautiful.html

int matchhere(char *regexp, char *text);

int matchstar(int c, char *regexp, char *text)
{
    int res = 0;
    do {    /* a * matches zero or more instances */
        if (matchhere(regexp, text)) {
            res = 1;
            break;
        }
    } while (*text != 0 && (*text++ == c || c == '.'));
    return res;
}     

int matchhere(char *regexp, char *text)
{
    int res = 0;
    char* chars = "*$.";
    if (regexp[0] == 0) {
        res = 1;
    } else 
    if (regexp[1] == chars[0]) {
        res = matchstar(regexp[0], regexp+2, text);
    } else 
    if (regexp[0] == chars[1] && regexp[1] == 0) {
        res = *text == 0;
    } else 
    if (*text!=0 && (regexp[0]==chars[2] || regexp[0]==*text)) {
        res = matchhere(regexp+1, text+1);
    }
    return res;
}

int match(char *regexp, char *text)
{
    char* anchor = "^";
    int res = 0;
    if (regexp[0] == anchor[0]) { 
        res = matchhere(regexp+1, text);
    } else
    do {    /* must look even if string is empty */
        if (matchhere(regexp, text)) {
            res = 1;
            break;
        }
    } while (*text++ != 0);
    return res;
}

char* POSITIVE = "assumes word senses. Within";

char* NEGATIVE = "in the U.S.A., people often";

struct In {
    char regex[30];
};

struct Out {
    int success;
};

int compute(struct In* input, struct Out* output) {
    char* regex = input->regex;
    int pos = match(regex, POSITIVE);
    int neg = match(regex, NEGATIVE);
    output->success = pos + 1-neg;
}
```
